# Generated by Django 5.1.2 on 2024-11-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_youtube_id_alter_video_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_id',
        ),
    ]
