# Dockerfile
FROM python:3.9


# Set the working directory
WORKDIR /app

# Install dependencies
COPY ./requirements/requirements.txt .
COPY ./requirements/requirements.ml.txt .
RUN pip install -r requirements.txt
RUN pip install -r requirements.ml.txt

# Copy the project
COPY . .