# Generated by Django 5.1.7 on 2025-04-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='categories.category'),
        ),
    ]
