# Generated by Django 5.1.2 on 2024-11-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='poster_path',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
