# Generated by Django 5.1.2 on 2024-10-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0002_watchlist_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='content',
        ),
    ]
