# Generated by Django 5.1.2 on 2024-11-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
