# Generated by Django 5.1.7 on 2025-03-24 15:15

import movie_recommendation_engine.exports.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=movie_recommendation_engine.exports.models.export_file_handler)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('ratings', 'Ratings'), ('movies', 'Movies')], default='ratings', max_length=20)),
                ('latest', models.BooleanField(default=True)),
            ],
        ),
    ]
