# Generated by Django 5.1.7 on 2025-04-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='type',
            field=models.CharField(choices=[('ratings', 'Ratings'), ('movies', 'Movies'), ('surprise', 'Surprise')], default='ratings', max_length=20),
        ),
    ]
